server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html

    location ~ \.php$ {
         include fastcgi_params;
         fastcgi_pass php-fpm:9000;
         fastcgi_index PATH_INFO $fastcgi_path_info;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

}